### PR TITLE
Change instructions to use invoke, not fabric.

### PR DESCRIPTION
**Pull request by eigenbeam**

### CODE REVIEW

**Review by mjbrodzik — COMMENTED** [review]
I am confused by steps 1. 2. and 5.  They are all talking about locations in the vagrant home directory, but I thought the convention was to have the project installed in /vagrant/?  So maybe some convention has changed and I don't know about it?

Also, step 7.  doesn't really make sense to me.  What is it telling me about pruning?  Maybe a use case would help here:
"What would the developer have to do to add a new set of regression files for an entirely new gsx sensor?"

**Comment by eigenbeam** [comment]
@mjbrodzik I'm guessing that the location is different because /vagrant will contain the contents of the `gsx-vm` project, which only defines the VM. We have a repo for defining the VM that you can run `gsx` on separate from `gsx` because `gsx` is just a python package and doesn't need to 'know' about VMs. So on the VM, the /vagrant directory doesn't contain the `gsx` or `gsx_regression` code/contents. It appears that we had to create a `/projects/PMESDR/vagrant` directory because there is a whole bunch of content in /projects/PMESDR that we presumably didn't want the vagrant user to touch, so we created a `vagrant` subdirectory that the vagrant user on a VM can write to. I believe that's why there are `kbeam`, `pmadden`, `brodzik`, and `mhardman` subdirs there.

As for step 7, and again I'm guessing here since I haven't used this project, I think it means that if updating expected SSMI output data, it will _appear_ as if AMSRE files have changed because the unix timestamp on them will be newer that what's in Git LFS. So I think it's saying, "get rid of all the files that you are not consciously touching and only copy over the files you know should be changing, ie, the SSMI files in this example."

**Comment by eigenbeam** [comment]
Pinging @flamingbear to review my comment above for accuracy.

**Comment by mjbrodzik** [comment]
Regarding the 1., 2. and 5. steps and the directories:  on the gsx-vm, the gsx project is in /vagrant/source/gsx.  So I think these comments are all referring to the wrong path?

Regarding step 7--I think this definitely needs clarification.  Why would the AMSRE files appear to change if you're just updating SSMI files?

**Comment by eigenbeam** [comment]
I don't know for sure, I'm just trying to interpret the words as I see them. :)  Need Matt to check this out and let us know.

**Comment by eigenbeam** [comment]
@mjbrodzik I don't see what you're seeing though: 
`vagrant@vmslushyalbedo:~$ ls -al /vagrant/source/gsx
ls: cannot access /vagrant/source/gsx: No such file or directory`

**Comment by mjbrodzik** [comment]
How bizarre!  Look:
vagrant@vmwintryshinshin:/vagrant/source$ ls
bitbucket-pipelines.yml  doc  gsx.egg-info  notebooks  recipe    spec-file.txt
CHANGELOG.md             gsx  MANIFEST.in   README.md  setup.py  tasks
vagrant@vmwintryshinshin:/vagrant/source$ cd gsx
vagrant@vmwintryshinshin:/vagrant/source/gsx$ ls -las
total 60
4 drwxr-xr-x 5 vagrant vagrant 4096 Jul  5 15:09 .
4 drwxr-xr-x 9 vagrant vagrant 4096 Jul  5 15:11 ..
4 drwxr-xr-x 2 vagrant vagrant 4096 Jul  5 15:09 ancillary
4 -rw-r--r-- 1 vagrant vagrant 1738 Jul  5 15:09 cdl.py
4 -rw-r--r-- 1 vagrant vagrant 1730 Jul  5 15:09 cli.py
4 -rw-r--r-- 1 vagrant vagrant   41 Jul  5 15:09 error.py
4 -rw-r--r-- 1 vagrant vagrant 3818 Jul  5 15:09 generate_year.py
4 -rw-r--r-- 1 vagrant vagrant 2706 Jul  5 15:09 hdf4_reader.py
4 -rw-r--r-- 1 vagrant vagrant   19 Jul  5 15:09 __init__.py
4 -rw-r--r-- 1 vagrant vagrant 1730 Jul  5 15:09 measure_overlap.py
4 -rw-r--r-- 1 vagrant vagrant 2612 Jul  5 15:09 spherical_geometry.py
4 drwxr-xr-x 2 vagrant vagrant 4096 Jul  5 15:09 strategies
4 drwxr-xr-x 3 vagrant vagrant 4096 Jul  5 15:09 test
4 -rw-r--r-- 1 vagrant vagrant 1948 Jul  5 15:09 transformer.py
4 -rw-r--r-- 1 vagrant vagrant 3149 Jul  5 15:09 utility.py
vagrant@vmwintryshinshin:/vagrant/source/gsx$

**Comment by flamingbear** [comment]
regarding the two previous comments: I think gsx is supposed to be checked out when you build a gsx-vm machine.  Not sure why @kbeamnsidc doesn't see it.

I walked through the steps to update the regression data and filled in the readme with correct information.  There was a couple of problems with the directions on how to run invoke tasks, that used to be fab tasks, and there were problems in the tasks themselves.   (see https://bitbucket.org/nsidc/gsx/pull-requests/93/add-contexts-to-task-calls/diff)

Let me know what you think of this.

**Comment by mjbrodzik** [comment]
The new instructions look really good and thorough to me.  Molly will use them to create SMMR regressions.  Thank you.

**Pull request merged**
